# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Users'),
        ),
    ]
