# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20160923_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='username_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subject_user',
            old_name='username_id',
            new_name='user',
        ),
    ]
