# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20160807_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
    ]
