# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20160810_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.Subject')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.User')),
            ],
        ),
    ]
